#240 added USER vars for vater and rous repo, edited verbiage of copy…
dev4vater/vater pull request #243
Opened 2022-05-10 21:02 UTC by Donovan-Medina

…ing ssh key to github, validated **go** downloads/installs correctly

2022-05-11 13:29 UTC, marissaeinhorn approved these changes
Looks good

2022-05-12 18:13 UTC, rylagek requested changes
line 162 needs to be updated to match your new verbiage - if rous is not already cloned, the setup script fails to clone it even with proper access permissions

2022-05-12 18:19 UTC, Donovan-Medina commented on control-services/bin/setup.sh
> +echo "Copy this key to github as an SSH key, call it $SETUP_REPO deploy. Press any key when done."
The key is not to a specific repo. It's part of github's settings of ssh keys -- they could theoretically could be called anything in github. 
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/36013253/168142378-e6969637-1f14-4131-834b-20ce17ea4025.png">

2022-05-12 18:48 UTC, Donovan-Medina commented on control-services/bin/setup.sh
> +    git clone git@github.com:$CONFIG_REPO/$CONFIG_REPO.git /home/control/$CONFIG_REPO
Good catch, added repo

2022-05-12 18:49 UTC, rylagek commented on control-services/bin/setup.sh
> +echo "Copy this key to github as an SSH key, call it $SETUP_REPO deploy. Press any key when done."
Interesting, so the way it's written now, whoever is setting up control has to add the keys to their account and their account needs proper access. That's substantially better than the setup process of adding keys to the repo owner's ssh keys. TIL. That's good

2022-05-12 18:54 UTC, Donovan-Medina commented on control-services/bin/setup.sh
> +echo "Copy this key to github as an SSH key, call it $SETUP_REPO deploy. Press any key when done."
👍 I learned that the hard way the other day. Still begs the question of long-term ownership over the private repo for the and implementing key management/rotation for when devs are no longer needing access to that repo or managing the control box in production.

2022-05-12 18:54 UTC, rylagek approved these changes

2022-05-12 18:54 UTC, merged